"""Test that gen_weapon_template.py emits ^Warhead_*_AA twin templates with
Range = ground * AA_RANGE_MULT (1.5) and ValidTargets: Air.

C44 / LANE 2 — the AA range law (DESIGN.md "The AA range law", 2026-09-08):
  - THREE classes only may carry AA range > ground range: scout_vehicle,
    armed_troop_transport, anti_air_vehicle — at 1.5x.
  - The 1.5x is GENERATED by gen_weapon_template.py (AA_RANGE_MULT), never
    hand-typed.
  - §8c applies: the generator must WRITE the value, and the test must assert
    the DERIVED number on a RESOLVED weapon through miniyaml.Ruleset.resolve_weapon.
"""

from __future__ import annotations

import pathlib
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT / "tools/audit")]

from miniyaml import Ruleset

AA_RANGE_MULT = 1.5
RATIO_EPSILON = 0.01


class AaRangeGenerationTests(unittest.TestCase):
    """Verify the generator's AA twin templates have the correct Range and
    ValidTargets when resolved through miniyaml."""

    @classmethod
    def setUpClass(cls):
        cls.rules = Ruleset(ROOT)

    def _resolved_range(self, wname: str) -> float | None:
        w = self.rules.resolve_weapon(wname)
        if w is None:
            return None
        v = w.get("Range")
        if v is None:
            return None
        try:
            return float(str(v).split(",")[0].strip())
        except (ValueError, TypeError):
            return None

    def _resolved_valid_targets(self, wname: str) -> str:
        w = self.rules.resolve_weapon(wname)
        if w is None:
            return ""
        return w.get("ValidTargets") or ""

    def _assert_aa_twin(self, ground_name: str, aa_name: str):
        """Assert the AA twin has Range = ground * 1.5 and ValidTargets: Air."""
        ground_range = self._resolved_range(ground_name)
        aa_range = self._resolved_range(aa_name)
        self.assertIsNotNone(ground_range, f"{ground_name} not resolved or no Range")
        self.assertIsNotNone(aa_range, f"{aa_name} not resolved or no Range")
        expected = ground_range * AA_RANGE_MULT
        self.assertAlmostEqual(
            aa_range, expected, delta=RATIO_EPSILON,
            msg=f"{aa_name} Range {aa_range} != ground {ground_range} * {AA_RANGE_MULT} = {expected}")
        aa_vt = self._resolved_valid_targets(aa_name)
        self.assertEqual("Air", aa_vt, f"{aa_name} ValidTargets should be 'Air', got '{aa_vt}'")

    def test_missileaa_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_MissileAA_Light", "^Warhead_MissileAA_Light_AA")
        self._assert_aa_twin("^Warhead_MissileAA_Medium", "^Warhead_MissileAA_Medium_AA")
        self._assert_aa_twin("^Warhead_MissileAA_Heavy", "^Warhead_MissileAA_Heavy_AA")

    def test_bullet_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_Bullet_Light", "^Warhead_Bullet_Light_AA")
        self._assert_aa_twin("^Warhead_Bullet_Medium", "^Warhead_Bullet_Medium_AA")
        self._assert_aa_twin("^Warhead_Bullet_Heavy", "^Warhead_Bullet_Heavy_AA")

    def test_laser_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_Laser_Light", "^Warhead_Laser_Light_AA")
        self._assert_aa_twin("^Warhead_Laser_Medium", "^Warhead_Laser_Medium_AA")
        self._assert_aa_twin("^Warhead_Laser_Heavy", "^Warhead_Laser_Heavy_AA")

    def test_flak_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_Flak_Light", "^Warhead_Flak_Light_AA")
        self._assert_aa_twin("^Warhead_Flak_Medium", "^Warhead_Flak_Medium_AA")
        self._assert_aa_twin("^Warhead_Flak_Heavy", "^Warhead_Flak_Heavy_AA")

    def test_arrow_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_Arrow_Light", "^Warhead_Arrow_Light_AA")
        self._assert_aa_twin("^Warhead_Arrow_Medium", "^Warhead_Arrow_Medium_AA")
        self._assert_aa_twin("^Warhead_Arrow_Heavy", "^Warhead_Arrow_Heavy_AA")

    def test_missileap_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_MissileAP_Light", "^Warhead_MissileAP_Light_AA")
        self._assert_aa_twin("^Warhead_MissileAP_Medium", "^Warhead_MissileAP_Medium_AA")
        self._assert_aa_twin("^Warhead_MissileAP_Heavy", "^Warhead_MissileAP_Heavy_AA")

    def test_missilehe_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_MissileHE_Light", "^Warhead_MissileHE_Light_AA")
        self._assert_aa_twin("^Warhead_MissileHE_Medium", "^Warhead_MissileHE_Medium_AA")
        self._assert_aa_twin("^Warhead_MissileHE_Heavy", "^Warhead_MissileHE_Heavy_AA")

    def test_ground_only_families_have_no_aa_twin(self):
        """CannonAP is ground-only (air=False) and must NOT have an AA twin."""
        self.assertIsNone(self.rules.resolve_weapon("^Warhead_CannonAP_Light_AA"))
        self.assertIsNone(self.rules.resolve_weapon("^Warhead_CannonAP_Medium_AA"))
        self.assertIsNone(self.rules.resolve_weapon("^Warhead_CannonAP_Heavy_AA"))

    def test_blend_photoncannon_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_PhotonCannon_Light", "^Warhead_PhotonCannon_Light_AA")
        self._assert_aa_twin("^Warhead_PhotonCannon_Medium", "^Warhead_PhotonCannon_Medium_AA")
        self._assert_aa_twin("^Warhead_PhotonCannon_Heavy", "^Warhead_PhotonCannon_Heavy_AA")

    def test_inherit_quantum_aa_twin_range_is_1_5x_ground(self):
        self._assert_aa_twin("^Warhead_Quantum_Light", "^Warhead_Quantum_Light_AA")
        self._assert_aa_twin("^Warhead_Quantum_Medium", "^Warhead_Quantum_Medium_AA")
        self._assert_aa_twin("^Warhead_Quantum_Heavy", "^Warhead_Quantum_Heavy_AA")


if __name__ == "__main__":
    unittest.main()
