#!/usr/bin/env python3
"""Renaming a weapon template must not move the balance model.

⛔ THE REGRESSION THIS EXISTS TO PREVENT (Astra, PR #372, 2026-09-13).

R12 renamed 34 structural migration helpers from `^Compatibility_*` to `^Warhead_*_Flat`. Two
balance consumers identified those helpers **by name prefix**, so the rename silently promoted
them into the model:

    target_model.pseudo_armor_mean   shield mean 180.28 -> 181.44, factor 0.5547 -> 0.5511
    extract_stats.warheads           33 `design_weapon_class` values moved

⛔ AND `audit_balance_drift` WENT GREEN AFTER A RE-EXTRACT WHILE PRESERVING ALL OF IT. That guard
compares yaml against the ledger; re-extracting simply wrote the new, wrong numbers into the
ledger and the two agreed again. **A green drift run proves the ledger matches the yaml, never
that the model is right.** Nothing in the suite could see the difference — hence this file.

The fix was to select helpers by SEMANTICS: a helper declares damage-typed warheads and gives
every one of them `Damage: 0`. That is rename-proof in both directions, which matters — one real
template, `^Warhead_TankBusterBeam_Unscoped_Flat`, also ends in `_Flat` but carries `Damage: 8000`,
so any suffix rule would have dropped a live profile.

⚠ THE PINNED NUMBERS BELOW ARE NOT LAWS. The Shield ladder is regenerated by
`gen_weapon_template` and legitimately moves. What must never move is the model's answer when only
a NAME changes — so the rename test is the real assertion and the pinned values are a tripwire.
Re-pin them in the same commit as a deliberate ladder change, never to make this file pass.
"""
from __future__ import annotations

import copy
import pathlib
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/balance"))
sys.path.insert(0, str(ROOT / "tools/audit"))

import target_model as tm          # noqa: E402
import extract_stats as es         # noqa: E402

# Measured on the tree that carries R12, with semantic selection restored.
SHIELD_MEAN = 180.2842
SHIELD_FACTOR = 0.5547
INERT_TEMPLATES = 33


class ShieldModelInvariance(unittest.TestCase):
    def test_shield_mean_and_factor_match_the_pre_rename_model(self):
        self.assertAlmostEqual(tm.pseudo_armor_mean("Shield"), SHIELD_MEAN, places=3)
        self.assertAlmostEqual(tm.shield_hp_factor(), SHIELD_FACTOR, places=4)

    def test_the_helper_cohort_is_selected_by_semantics(self):
        inert = tm.damage_inert_templates()
        self.assertEqual(len(inert), INERT_TEMPLATES)
        # Every selected template really is damage-inert...
        rs = tm._ruleset()
        for name in inert:
            self.assertTrue(tm.is_damage_inert(rs.weapons[name]), name)
        # ...and a live template that merely SHARES the suffix is not selected.
        live = "^Warhead_TankBusterBeam_Unscoped_Flat"
        if live in rs.weapons:
            self.assertNotIn(live, inert)
            self.assertFalse(tm.is_damage_inert(rs.weapons[live]))

    def test_a_pure_rename_cannot_move_the_shield_mean(self):
        """⭐ THE LOAD-BEARING TEST. Rename every helper and demand the same answer.

        This is what a prefix filter cannot survive and a semantic one cannot notice.
        """
        rs = tm._ruleset()
        before = tm.pseudo_armor_mean("Shield")
        renamed = {}
        for name, node in rs.weapons.items():
            if name.startswith("^") and tm.is_damage_inert(node):
                clone = copy.deepcopy(node)
                new = name + "_RenamedByTest"
                clone.key = new
                renamed[new] = clone
        self.assertTrue(renamed, "no helper templates found — the fixture is inert")
        original = rs.weapons
        try:
            swapped = {n: w for n, w in original.items()
                       if not (n.startswith("^") and tm.is_damage_inert(w))}
            swapped.update(renamed)
            rs.weapons = swapped
            tm.pseudo_armor_mean.cache_clear()
            tm._INERT_CACHE.clear()
            after = tm.pseudo_armor_mean("Shield")
        finally:
            rs.weapons = original
            tm.pseudo_armor_mean.cache_clear()
            tm._INERT_CACHE.clear()
        self.assertAlmostEqual(before, after, places=6,
                               msg="renaming the helpers moved the shield mean")


class WeaponClassInvariance(unittest.TestCase):
    def test_helpers_never_enter_a_weapon_class_list(self):
        rs = tm._ruleset()
        inert = tm.damage_inert_templates(rs)
        self.assertTrue(inert)
        leaked = []
        for wname in rs.weapons:
            if wname.startswith("^"):
                continue
            for t in es.warheads(rs, wname):
                if t in inert:
                    leaked.append((wname, t))
        self.assertEqual(leaked, [], f"{len(leaked)} weapon(s) collected a migration helper")

    def test_supplementary_twins_never_bear_a_class(self):
        """⭐ THE SECOND COHORT, found only by checking against the pre-rename ledger.

        `^Compatibility_Railgun_ExtraDamage` became `^Warhead_Railgun_ExtraDamage` in R12 and
        started being collected as a class template. An ExtraDamage twin supplements a main
        warhead; it is never the weapon's class — and counting it also pushed weapons past the
        2-warhead cap, so `MigMissiles_AA` lost its class entirely to a bogus "illegal mix".
        """
        rs = tm._ruleset()
        nonclass = tm.non_class_templates(rs)
        twins = [n for n in rs.weapons
                 if n.startswith("^") and tm.is_supplementary_template(rs.weapons[n])]
        self.assertTrue(twins, "no supplementary twin templates found — fixture is inert")
        for t in twins:
            self.assertIn(t, nonclass, t)
        for wname in rs.weapons:
            if wname.startswith("^"):
                continue
            self.assertFalse([t for t in es.warheads(rs, wname) if t in twins],
                             f"{wname} collected a supplementary twin as a class template")

    def test_a_helper_would_otherwise_have_changed_a_class(self):
        """The guard above is only meaningful if the helpers ARE class-bearing names.

        Without this, deleting every `^Warhead_*_Flat` template would make the test above pass
        vacuously — a guard that cannot fail is not a guard.
        """
        inert = tm.damage_inert_templates()
        classed = [n for n in inert
                   if es.weapon_class_from_types([n]) is not None]
        self.assertTrue(classed,
                        "no helper maps to a weapon class, so this cohort could not have "
                        "moved design_weapon_class — re-check the fixture")


if __name__ == "__main__":
    unittest.main()
