"""Audit copied inheritance keys in supplied DTA client-generated INIs.

Does not run preprocessing or re-inherit after overlay merging. The client keeps
BaseSection in generated output, so its presence alone is not an unresolved gap.
"""
import hashlib
from extract_ini_units import read_ini


def audit(path):
    raw = path.read_bytes()
    generated = raw.decode("latin-1").startswith("; generated by DTA CnCNet client,")
    sections = read_ini(path)
    inherited = {}
    for name, fields in sections.items():
        if not fields.get("BaseSection"):
            continue
        problems, visited = [], {name}
        child = name
        while sections[child].get("BaseSection"):
            parent = sections[child]["BaseSection"]
            if parent in visited:
                problems.append("inheritance cycle: " + parent)
                break
            if parent not in sections:
                problems.append("missing parent: " + parent)
                break
            missing = sorted(set(sections[parent]) - set(sections[child]))
            if missing:
                problems.append(child + " missing parent keys: " + ", ".join(missing))
            visited.add(parent)
            child = parent
        inherited[name] = {
            "status": "generated parent keys present" if generated and not problems else "not resolved",
            "problems": problems if generated else ["not marked as client-generated", *problems]}
    return {"file": path.name, "sha256": hashlib.sha256(raw).hexdigest(),
            "generated_header": generated, "sections": len(sections),
            "inherited": inherited,
            "scope": "Copied-key closure only; not runtime or client-version certification."}
