#!/usr/bin/env python3
"""Cameo C# coverage collector + per-file report.

Collects line/branch coverage of the OpenRA.Mods.Cameo.Test NUnit suite
via the `dotnet-coverage` global tool (CLR profiler — coverlet's
collector/msbuild/console mechanisms produce all-zero hits in this
custom EngineRootPath layout), parses the resulting Cobertura XML, and
emits a per-file table scoped to the bot-module source trees plus a JSON
baseline for the ratchet in tools/audit/audit_test_coverage.py.

Usage:
    python tools/ai/coverage_report.py --collect --xml out/coverage.xml
    python tools/ai/coverage_report.py --xml out/coverage.xml --report docs/coverage.md
    python tools/ai/coverage_report.py --xml out/coverage.xml --write-baseline tools/tests/coverage_baseline.json

Install prerequisite once:
    dotnet tool install -g dotnet-coverage
"""
import argparse
import json
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TEST_DLL = os.path.join(REPO_ROOT, "engine", "bin", "OpenRA.Mods.Cameo.Test.dll")
DEFAULT_XML = os.path.join(REPO_ROOT, "TestResults", "coverage.cobertura.xml")
DEFAULT_BASELINE = os.path.join(REPO_ROOT, "tools", "tests", "coverage_baseline.json")

# Per-file report scope: bot-module sources in both mod assemblies.
# CA hosts the upstream-style squad/manager bot modules; Cameo hosts the
# Cameo-specific modular-bot tree (Traits/BotModules/** plus the
# bot-named controllers at Traits root).
SCOPE_PATTERNS = [
    re.compile(r"OpenRA\.Mods\.CA[\\/]Traits[\\/]BotModules[\\/]"),
    re.compile(r"OpenRA\.Mods\.Cameo[\\/]Traits[\\/]BotModules[\\/]"),
    re.compile(r"OpenRA\.Mods\.Cameo[\\/]Traits[\\/][^\\/]*Bot[^\\/]*\.cs$"),
]


def relpath(path):
    p = os.path.normpath(path)
    root = os.path.normpath(REPO_ROOT)
    if p.lower().startswith(root.lower() + os.sep):
        return p[len(root) + 1:].replace("\\", "/")
    return p.replace("\\", "/")


def in_scope(path):
    return any(pat.search(path) for pat in SCOPE_PATTERNS)


def collect(xml_path):
    """Run dotnet-coverage over the built test assembly."""
    if not os.path.isfile(TEST_DLL):
        sys.exit(
            f"Test assembly not found: {TEST_DLL}\n"
            "Build it first: dotnet build OpenRA.Mods.Cameo.Test -c Release"
        )
    os.makedirs(os.path.dirname(os.path.abspath(xml_path)), exist_ok=True)
    cmd = [
        "dotnet-coverage", "collect",
        "-f", "cobertura",
        "-o", os.path.abspath(xml_path),
        f"dotnet vstest \"{TEST_DLL}\"",
    ]
    print("Running:", " ".join(cmd[:-1]), repr(cmd[-1]))
    proc = subprocess.run(cmd, cwd=REPO_ROOT)
    if proc.returncode != 0:
        sys.exit(f"dotnet-coverage exited {proc.returncode}")
    if not os.path.isfile(xml_path):
        sys.exit(f"Coverage XML not produced at {xml_path}")


def parse(xml_path):
    """Cobertura -> {relpath: {lines, lines_hit, branches, branches_hit}}."""
    root = ET.parse(xml_path).getroot()
    rows = {}
    for cls in root.findall(".//class"):
        fn = cls.get("filename")
        if not fn or not in_scope(fn):
            continue
        rel = relpath(fn)
        rec = rows.setdefault(rel, {"lines": 0, "lines_hit": 0, "branches": 0, "branches_hit": 0})
        for ln in cls.findall(".//line"):
            rec["lines"] += 1
            if int(ln.get("hits", "0")) > 0:
                rec["lines_hit"] += 1
            if ln.get("branch", "").lower() == "true":
                # condition-coverage="50% (1/2)" -> 1 of 2 outcomes covered
                m = re.search(r"\((\d+)/(\d+)\)", ln.get("condition-coverage", ""))
                if m:
                    rec["branches_hit"] += int(m.group(1))
                    rec["branches"] += int(m.group(2))
    return rows


def render_markdown(rows):
    def rate(a, b):
        return (100.0 * a / b) if b else 0.0

    total_l = sum(r["lines"] for r in rows.values())
    total_lh = sum(r["lines_hit"] for r in rows.values())
    total_b = sum(r["branches"] for r in rows.values())
    total_bh = sum(r["branches_hit"] for r in rows.values())

    out = [
        "# Bot-module coverage report",
        "",
        "Generated by `tools/ai/coverage_report.py` from `dotnet-coverage` output.",
        "Scope: `OpenRA.Mods.CA/Traits/BotModules/**`, `OpenRA.Mods.Cameo/Traits/BotModules/**`, "
        "and `OpenRA.Mods.Cameo/Traits/*Bot*.cs`.",
        "",
        f"**Totals: line {rate(total_lh, total_l):.1f}% ({total_lh}/{total_l}), "
        f"branch {rate(total_bh, total_b):.1f}% ({total_bh}/{total_b}), "
        f"{sum(1 for r in rows.values() if r['lines'])} files with instrumented lines "
        f"of {len(rows)} files in scope.**",
        "",
        "| File | Line % | Lines | Branch % | Branches |",
        "|---|---|---|---|---|",
    ]
    worst_first = sorted(rows.items(), key=lambda kv: rate(kv[1]["lines_hit"], kv[1]["lines"]))
    for path, r in worst_first:
        out.append(
            f"| `{path}` | {rate(r['lines_hit'], r['lines']):.1f} | "
            f"{r['lines_hit']}/{r['lines']} | {rate(r['branches_hit'], r['branches']):.1f} | "
            f"{r['branches_hit']}/{r['branches']} |"
        )
    return "\n".join(out) + "\n"


def baseline_doc(rows):
    def rate(a, b):
        return (100.0 * a / b) if b else 0.0

    return {
        "files": {
            path: {
                "line_rate": round(rate(r["lines_hit"], r["lines"]), 2),
                "branch_rate": round(rate(r["branches_hit"], r["branches"]), 2),
                "lines": r["lines"],
            }
            for path, r in sorted(rows.items())
        }
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--collect", action="store_true", help="run dotnet-coverage over the test assembly first")
    ap.add_argument("--xml", default=DEFAULT_XML, help="cobertura xml path (input, or output with --collect)")
    ap.add_argument("--report", help="write markdown report here (default: stdout)")
    ap.add_argument("--write-baseline", help="write per-file ratchet baseline JSON here")
    args = ap.parse_args()

    if args.collect:
        collect(args.xml)
    if not os.path.isfile(args.xml):
        sys.exit(f"Coverage XML not found: {args.xml} (run with --collect first)")

    rows = parse(args.xml)
    if not rows:
        sys.exit("No in-scope coverage data — XML produced zero hits? Check the collector ran the tests.")

    md = render_markdown(rows)
    if args.report:
        os.makedirs(os.path.dirname(os.path.abspath(args.report)), exist_ok=True)
        with open(args.report, "w", encoding="utf-8") as f:
            f.write(md)
        print(f"Report written: {args.report}")
    else:
        sys.stdout.buffer.write(md.encode("utf-8", "replace"))

    if args.write_baseline:
        os.makedirs(os.path.dirname(os.path.abspath(args.write_baseline)), exist_ok=True)
        with open(args.write_baseline, "w", encoding="utf-8") as f:
            json.dump(baseline_doc(rows), f, indent=1)
            f.write("\n")
        print(f"Baseline written: {args.write_baseline}")


if __name__ == "__main__":
    main()
