#!/usr/bin/env python3
"""Fit frozen LEARN-FIGHT rows from anonymous P0 engagement records.

This deliberately has no player identity input.  Rows pool from
faction__vs__faction to faction, family and any; only cells with the published
minimum evidence are emitted.  Runtime consumes threshold rows behind BV_learn_fight.
Calibration/value rows are provenance for the existing tier-1 engagement-prior fit:
fit_engagement_priors.py remains the sole delivery×armour correction writer.
"""
from __future__ import annotations

import argparse
import json
import pathlib
from collections import defaultdict
from dataclasses import dataclass

CALIBRATION_MIN = 200
THRESHOLD_MIN = 150
NEUTRAL = 1000


@dataclass
class Totals:
    n: int = 0
    predicted: int = 0
    actual: int = 0
    trade: int = 0
    wins: int = 0


def read_records(paths: list[pathlib.Path]):
    for path in paths:
        if path.is_dir():
            yield from read_records(sorted(path.rglob("cameo-ai-engagements.jsonl")))
            continue
        try:
            with path.open(encoding="utf-8") as stream:
                for line in stream:
                    try:
                        row = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if row.get("record") == "engagement":
                        yield row
        except OSError:
            continue


def scope_chain(own: str, enemy: str):
    family = own.split("_", 1)[0] if "_" in own else ""
    if own and enemy:
        yield f"{own}__vs__{enemy}"
    if own:
        yield own
    if family:
        yield f"family_{family}"
    yield "any"


def integer_median(values: list[int]) -> int:
    values = sorted(values)
    return values[(len(values) - 1) // 2] if values else 0


def facts(row: dict):
    seen = row.get("seen") or {}
    start = seen.get("start") or {}
    outcome = row.get("outcome") or {}
    truth = row.get("truth") or {}
    own, enemy = row.get("faction") or "", row.get("enemy_faction") or ""
    # P0 labels retain faction only.  Never accept an old player/name field as a key.
    if not own:
        return None
    own_value = int(start.get("own_committed_value") or 0) + int(start.get("own_defence_value") or 0)
    enemy_value = int((truth.get("start") or {}).get("enemy_unit_value") or start.get("enemy_unit_value") or 0)
    predicted = int(start.get("predicted_enemy_surviving_permille") or 0)
    killed = int(outcome.get("enemy_killed_value") or truth.get("enemy_loss_value") or 0)
    lost = int(outcome.get("own_lost_value") or outcome.get("own_lost_unit_value") or 0)
    if own_value <= 0 or enemy_value <= 0 or not 0 < predicted < 1000:
        return None
    expected = max(1, enemy_value * (1000 - predicted) // 1000)
    actual = min(enemy_value, max(0, killed))
    return own, enemy, expected, actual, actual - min(own_value, max(0, lost))


def fit(records):
    totals = defaultdict(Totals)
    threshold_observations = defaultdict(list)
    for row in records:
        item = facts(row)
        if item is None:
            continue
        own, enemy, expected, actual, trade = item
        for scope in scope_chain(own, enemy):
            total = totals[scope]
            total.n += 1
            total.predicted += expected
            total.actual += actual
            total.trade += trade
            if trade >= 0:
                total.wins += 1
            # A conservative threshold observation: good trades can tolerate lower
            # predicted ratio; bad trades tighten it.  It is bounded later.
            threshold_observations[scope].append(45 if trade >= 0 else 65)

    rows = {}
    for scope, total in sorted(totals.items()):
        if total.n < THRESHOLD_MIN:
            continue
        calibration = (max(500, min(2000, total.actual * NEUTRAL // max(1, total.predicted)))
                       if total.n >= CALIBRATION_MIN else None)
        # Effective value is a deterministic, cost-free summary of observed value
        # traded.  It lets review compare cells without becoming a second combat model.
        effective = (max(500, min(2000, (total.wins * NEUTRAL + total.n // 2) * NEUTRAL // total.n))
                     if total.n >= CALIBRATION_MIN else None)
        retreat = max(1, min(100, integer_median(threshold_observations[scope])))
        # Preserve hysteresis and never reduce the engage threshold below retreat.
        engage = max(100, min(300, 150 + (retreat - 50)))
        rows[scope] = (total.n, calibration, effective, retreat, engage)
    return rows


def render(rows):
    out = [
        "# GENERATED by tools/ai/fit_fight_learning.py --write; do not edit by hand.",
        "# Anonymous scopes only; runtime uses reviewed integer rows and falls back when a row is absent.",
        "BotFightLearning:",
        "\tSchema: 1",
        f"\tCalibrationMinimumSamples: {CALIBRATION_MIN}",
        f"\tThresholdMinimumSamples: {THRESHOLD_MIN}",
    ]
    for scope, (n, calibration, effective, retreat, engage) in rows.items():
        out.append(f"\tEvidence@{scope}: {n}")
        if calibration is not None:
            out.append(f"\tCalibrationMilli@{scope}: {calibration}")
            out.append(f"\tEffectiveValueMilli@{scope}: {effective}")
        out += [f"\tRetreatRatioPct@{scope}: {retreat}", f"\tEngageMarginPct@{scope}: {engage}"]
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="+", type=pathlib.Path)
    parser.add_argument("--write", type=pathlib.Path)
    args = parser.parse_args()
    rows = fit(read_records(args.paths))
    text = render(rows)
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(text, encoding="utf-8")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
