#!/usr/bin/env python3
"""gen_projectiles.py — LAYER 2 of the weapon 3-way split (see
docs/design/WEAPON_3WAY_SPLIT.md).

Extracts the `Projectile:` block from each old full-stack central template in
weapons.yaml and re-emits it as a standalone `^Projectile<Family>_<Level>`
template, verbatim (behavior preserved). Prints the library to stdout.

Usage: python tools/balance/gen_projectiles.py > projectile_library.yaml
"""
from __future__ import annotations
import os, re, sys

WY = os.path.join(os.path.dirname(__file__), "..", "..", "mods", "cameo", "weapons", "weapons.yaml")

# old template -> (projectile family, level). Old templates with no own Projectile
# block (Shrapnel/HeavyBomb/Nuclear = dropped bombs) and the STAY specials are omitted.
PMAP = {
    "SmallArms": ("Bullet", "Light"), "Chaingun": ("Bullet", "Medium"),
    "FlakWeapon": ("Flak", "Medium"), "HeavyAAWeapon": ("Flak", "Heavy"),
    "TankDestroyerCannon": ("Shell", "Light"), "MediumCannon": ("Shell", "Medium"), "HeavyCannon": ("Shell", "Heavy"),
    "LightMissile": ("Missile", "Light"), "MediumMissile": ("Missile", "Medium"), "HeavyMissile": ("Missile", "Heavy"),
    "LaserWeapon": ("Laser", "Heavy"), "RailgunWeapon": ("Railgun", "Heavy"),
    "TeslaWeapon": ("Lightning", "Heavy"), "TeslaChargedWeapon": ("Lightning", "Super"),
    "LightFlameWeapon": ("Flame", "Light"), "MediumFlameWeapon": ("Flame", "Medium"), "HeavyFlameWeapon": ("Flame", "Heavy"),
    "LightChemicalWeapon": ("Chem", "Light"), "MediumChemicalWeapon": ("Chem", "Medium"), "HeavyChemicalWeapon": ("Chem", "Heavy"),
    "Grenade": ("Grenade", "Light"),
    "SwordWeapon": ("Melee", "Medium"), "ArrowWeapon": ("Arrow", "Light"), "MagicWeapon": ("Magic", "Heavy"),
}
LEVELORDER = {"Light": 0, "Medium": 1, "Heavy": 2, "Super": 3}


def blocks_of(path):
    lines = open(path, encoding="utf-8").read().split("\n")
    out, cur = {}, None
    for ln in lines:
        m = re.match(r"^\^(\w+):\s*$", ln)
        if m:
            cur = m.group(1); out[cur] = []; continue
        if re.match(r"^\S", ln) and not ln.startswith("^"):
            cur = None
        if cur is not None:
            out[cur].append(ln)
    return out


def extract_projectile(body_lines):
    out, grab = [], False
    for ln in body_lines:
        if re.match(r"^\tProjectile:", ln):
            grab = True; out.append(ln); continue
        if grab:
            if re.match(r"^\t\t", ln) or ln.strip() == "":
                out.append(ln)
            else:
                break
    while out and out[-1].strip() == "":
        out.pop()
    return out


def main():
    blocks = blocks_of(WY)
    emitted, order = {}, []
    for old, (fam, lvl) in PMAP.items():
        b = blocks.get(old)
        if not b:
            continue
        proj = extract_projectile(b)
        if not proj:
            continue
        # The firing/LAUNCH sound (top-level Report/StartReport) is defined by the delivery
        # method → it belongs to the PROJECTILE layer (a cannon and a missile launch differently).
        report = [l for l in b if re.match(r"^\t(Report|StartReport|StartBurstReport):", l)]
        name = f"Projectile_{fam}_{lvl}"
        emitted[name] = "\n".join([f"^{name}:"] + report + proj)
        order.append(name)
    order.sort(key=lambda n: (n.split("_")[1], LEVELORDER.get(n.split("_")[-1], 9)))
    print("# LAYER 2 — PROJECTILE templates (3-way split). GENERATED by")
    print("# tools/balance/gen_projectiles.py from the old full-stack templates. DO NOT hand-edit.")
    print()
    for n in order:
        print(emitted[n]); print()
    print(f"# {len(order)} projectile templates", file=sys.stderr)


if __name__ == "__main__":
    main()
